FROM mcr.microsoft.com/devcontainers/python:${templateOption:imageVariant}

# sets the cuda variables for CUDA support in docker
#ENV NVIDIA_VISIBLE_DEVICES ${templateOption:visibleGpus}
#ENV NVIDIA_DRIVER_CAPABILITIES ${templateOption:gpuCapabilities}